### PR TITLE
Rating toast

### PR DESCRIPTION
**Pull request by lomesshh**

### CODE REVIEW

**Review by scjuly19 — APPROVED** [review]

**Comment by Logan1x** [comment]
Hey Lomesh, Recommend you connect your repo to netlify or vercel. So that each time you push a pr/commit, it generates deployment previews. It makes easier for the reviewer to see visual changes :)

**Comment by lomesshh** [comment]
> Hey Lomesh, Recommend you connect your repo to netlify or vercel. So that each time you push a pr/commit, it generates deployment previews. It makes easier for the reviewer to see visual changes :)

for sure ! ill keep this in mind from next time

**Comment by lomesshh** [comment]
> Hey Lomesh, Recommend you connect your repo to netlify or vercel. So that each time you push a pr/commit, it generates deployment previews. It makes easier for the reviewer to see visual changes :)

for sure ! ill keep this in mind from next time 
as of now is it ok ?  or any changes in code you would suggest.

**Review by Logan1x — APPROVED** [review]

**Comment by Logan1x** [comment]
You can go ahead and merge this branch.

**Pull request merged**
